{
  "openapi" : "3.0.3",
  "info" : {
    "title" : "Mijn Rooster API",
    "description" : "Het standaard Auth token voor development is nu **oqkd1ogtDkOUcsa33HOdXvt76uXiTdfwxYGMqWem**. Het authenticatie proces wordt waarschijnlijk in de toekomst veranderd.",
    "contact" : { },
    "version" : "1.0.0"
  },
  "servers" : [ {
    "url" : "http://545959.leerlingsites.nl/pws/api"
  }, {
    "url" : "http://localhost:8000"
  } ],
  "security" : [ {
    "bearerAuth" : []
  } ],
  "paths" : {
    "/v1/school/{schoolInSchoolYear}/user/{userId}" : {
      "get" : {
        "summary" : "User endpoint",
        "description" : "This endpoint makes an HTTP GET request to retrieve information about a user in a specific school and school year. The request should include the school ID and the user ID in the URL parameters.\n\n### Request\n- `:schoolInSchoolYear` (path parameter) - The ID of the school in the specific school year.\n    \n- `:userId` (path parameter) - The ID of the user.\n- `type=` (optional) - The type of user: student or teacher\n    \n\n### Response\n\nThe response will have a status code of 200 and a content type of application/json. The response body will include an array of user data, with fields such as code, first name, prefix, and last name.\n\nExample response:\n\n``` json\n{\n    \"statusCode\": 200,\n    \"message\": \"\",\n    \"details\": \"\",\n    \"rowCount\": 1,\n    \"data\": [\n        {\n            \"code\": \"\",\n            \"firstName\": \"\",\n            \"prefix\": \"\",\n            \"lastName\": \"\"\n        }\n    ]\n}\n\n ```\n\n#### JSON Schema\n\n``` json\n{\n    \"type\": \"object\",\n    \"properties\": {\n        \"statusCode\": {\n            \"type\": \"number\"\n        },\n        \"message\": {\n            \"type\": \"string\"\n        },\n        \"details\": {\n            \"type\": \"string\"\n        },\n        \"rowCount\": {\n            \"type\": \"number\"\n        },\n        \"data\": {\n            \"type\": \"array\",\n            \"items\": {\n                \"type\": \"object\",\n                \"properties\": {\n                    \"code\": {\n                        \"type\": \"string\"\n                    },\n                    \"firstName\": {\n                        \"type\": \"string\"\n                    },\n                    \"prefix\": {\n                        \"type\": \"string\"\n                    },\n                    \"lastName\": {\n                        \"type\": \"string\"\n                    }\n                }\n            }\n        }\n    }\n}\n\n ```",
        "operationId" : "userEndpoint",
        "parameters" : [ {
          "name" : "schoolInSchoolYear",
          "in" : "path",
          "description" : "Id of the school in specific schoolyear",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "1001702"
          }
        }, {
          "name" : "userId",
          "in" : "path",
          "description" : "The codes/abbreviations of the user (e.g. GIJS or 545959)",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "vis"
          }
        }, {
          "name" : "type",
          "in" : "query",
          "description" : "The type of user: student or teacher",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "teacher"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Default / Teacher / Student",
            "headers" : {
              "Access-Control-Allow-Headers" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Content-Type, Authorization"
                }
              },
              "Access-Control-Allow-Methods" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "GET, POST, PUT, DELETE"
                }
              },
              "Access-Control-Allow-Origin" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "*"
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "close"
                }
              },
              "Date" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Tue, 05 Nov 2024 19:09:51 GMT"
                }
              },
              "Host" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "localhost:8000"
                }
              },
              "X-Powered-By" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "PHP/8.3.12"
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200"
                },
                "examples" : {
                  "Default" : {
                    "value" : {
                      "data" : [ {
                        "code" : "vis",
                        "firstName" : "Sienna",
                        "lastName" : "Visscher",
                        "prefix" : "van der"
                      } ],
                      "details" : "",
                      "message" : "",
                      "rowCount" : 1,
                      "statusCode" : 200
                    }
                  },
                  "Student" : {
                    "value" : {
                      "data" : [ {
                        "code" : "138563",
                        "firstName" : "Mathis",
                        "lastName" : "Leenders",
                        "prefix" : ""
                      } ],
                      "details" : "",
                      "message" : "",
                      "rowCount" : 1,
                      "statusCode" : 200
                    }
                  },
                  "Teacher" : {
                    "value" : {
                      "data" : [ {
                        "code" : "vis",
                        "firstName" : "Sienna",
                        "lastName" : "Visscher",
                        "prefix" : "van der"
                      } ],
                      "details" : "",
                      "message" : "",
                      "rowCount" : 1,
                      "statusCode" : 200
                    }
                  }
                }
              }
            }
          },
          "404" : {
            "description" : "Not Found",
            "headers" : {
              "Access-Control-Allow-Headers" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Content-Type, Authorization"
                }
              },
              "Access-Control-Allow-Methods" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "GET, POST, PUT, DELETE"
                }
              },
              "Access-Control-Allow-Origin" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "*"
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "close"
                }
              },
              "Date" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Tue, 05 Nov 2024 19:10:10 GMT"
                }
              },
              "Host" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "localhost:8000"
                }
              },
              "X-Powered-By" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "PHP/8.3.12"
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_404"
                },
                "examples" : {
                  "Not Found" : {
                    "value" : {
                      "data" : [ ],
                      "details" : "The user could not be found in the Zermelo API",
                      "message" : "User not found",
                      "rowCount" : 0,
                      "statusCode" : 404
                    }
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/v1/schedule/{userid}" : {
      "get" : {
        "summary" : "Schedule endpoint",
        "description" : "This endpoint makes an HTTP GET request to retrieve appointments in the schedule of the given user. The request should include the userId in the URL parameters. Start and end are optional, otherwise the current week is given.\n\n### Request\n\n- `:userId` (path parameter) - The ID of the user (for example 545959 or GIJS)\n    \n- `start=` (optional) - UTC Unix time of the start of this appointment. This is the first second this appointment is taking place\n    \n- `end=` (optional) - UTC Unix time of the end of this appointment. This is the last second this appointment is taking place\n    \n\n### Response\n\nThe response will have a status code of 200 and a content type of `application/json`. The response body will include an array of user data, with fields such as code, first name, prefix, and last name.  \nExample response:\n\n``` json\n{\n    \"statusCode\": 200,\n    \"message\": \"\",\n    \"details\": \"\",\n    \"rowCount\": 1,\n    \"data\": [\n        {\n            \"id\": 0,\n            \"appointmentInstance\": 0,\n            \"start\": \"\",\n            \"end\": \"\",\n            \"locations\": [\"\"],\n            \"subjects\": [\"\"],\n            \"teachers\": [\"\"]\n        }\n    ]\n}\n\n ```\n\nJSON Schema\n\n``` json\n{\n    \"type\": \"object\",\n    \"properties\": {\n        \"statusCode\": {\n            \"type\": \"number\"\n        },\n        \"message\": {\n            \"type\": \"string\"\n        },\n        \"details\": {\n            \"type\": \"string\"\n        },\n        \"rowCount\": {\n            \"type\": \"number\"\n        },\n        \"data\": {\n            \"type\": \"array\",\n            \"items\": {\n                \"type\": \"object\",\n                \"properties\": {\n                    \"id\": {\n                        \"type\": \"number\"\n                    },\n                    \"appointmentInstance\": {\n                        \"type\": \"number\"\n                    },\n                    \"start\": {\n                        \"type\": \"string\"\n                    },\n                    \"end\": {\n                        \"type\": \"string\"\n                    },\n                    \"locations\": {\n                        \"type\": \"array\",\n                        \"items\": {\n                            \"type\": \"string\"\n                        }\n                    },\n                    \"subjects\": {\n                        \"type\": \"array\",\n                        \"items\": {\n                            \"type\": \"string\"\n                        }\n                    },\n                    \"teachers\": {\n                        \"type\": \"array\",\n                        \"items\": {\n                            \"type\": \"string\"\n                        }\n                    }\n                }\n            }\n        }\n    }\n}\n\n ```",
        "operationId" : "scheduleEndpoint",
        "parameters" : [ {
          "name" : "userid",
          "in" : "path",
          "description" : "The codes/abbreviations of the user (e.g. GIJS or 545959)",
          "required" : true,
          "style" : "simple",
          "explode" : false,
          "schema" : {
            "type" : "string",
            "example" : "138563"
          }
        }, {
          "name" : "start",
          "in" : "query",
          "description" : "UTC Unix time of the start of this appointment. This is the first second this appointment is taking place",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "1730678400"
          }
        }, {
          "name" : "end",
          "in" : "query",
          "description" : "UTC Unix time of the end of this appointment. This is the last second this appointment is taking place",
          "required" : false,
          "style" : "form",
          "explode" : true,
          "schema" : {
            "type" : "string",
            "example" : "1731283199"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "Default / Begin/end Date",
            "headers" : {
              "Access-Control-Allow-Headers" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Content-Type, Authorization"
                }
              },
              "Access-Control-Allow-Methods" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "GET, POST, PUT, DELETE"
                }
              },
              "Access-Control-Allow-Origin" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "*"
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "close"
                }
              },
              "Date" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Tue, 05 Nov 2024 19:11:37 GMT"
                }
              },
              "Host" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "localhost:8000"
                }
              },
              "X-Powered-By" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "PHP/8.3.12"
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_200_1"
                },
                "examples" : {
                  "Begin/end Date" : {
                    "value" : {
                      "data" : [ {
                        "appointmentInstance" : 3277578,
                        "end" : "1730807100",
                        "id" : 3435563,
                        "locations" : [ "a212" ],
                        "start" : "1730804700",
                        "subjects" : [ "gd" ],
                        "teachers" : [ "too" ]
                      }, {
                        "appointmentInstance" : 3278630,
                        "end" : "1730971800",
                        "id" : 3435143,
                        "locations" : [ "a152" ],
                        "start" : "1730968800",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3276826,
                        "end" : "1730719800",
                        "id" : 3434913,
                        "locations" : [ "b129" ],
                        "start" : "1730716800",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3277993,
                        "end" : "1730885400",
                        "id" : 3435856,
                        "locations" : [ "a030" ],
                        "start" : "1730882400",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3276789,
                        "end" : "1730709600",
                        "id" : 3434727,
                        "locations" : [ "a118" ],
                        "start" : "1730706600",
                        "subjects" : [ "gs" ],
                        "teachers" : [ "wes" ]
                      }, {
                        "appointmentInstance" : 3277464,
                        "end" : "1730792400",
                        "id" : 3435223,
                        "locations" : [ "a270" ],
                        "start" : "1730790000",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3278070,
                        "end" : "1730965800",
                        "id" : 3436163,
                        "locations" : [ "a268" ],
                        "start" : "1730962800",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3277065,
                        "end" : "1730716800",
                        "id" : 3434858,
                        "locations" : [ "b129" ],
                        "start" : "1730713800",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3277423,
                        "end" : "1730879400",
                        "id" : 3435716,
                        "locations" : [ "a252" ],
                        "start" : "1730876400",
                        "subjects" : [ "gd" ],
                        "teachers" : [ "too" ]
                      }, {
                        "appointmentInstance" : 3278979,
                        "end" : "1731072900",
                        "id" : 3436874,
                        "locations" : [ "binask10" ],
                        "start" : "1731069900",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3278832,
                        "end" : "1731065400",
                        "id" : 3436675,
                        "locations" : [ "bv1" ],
                        "start" : "1731059400",
                        "subjects" : [ "bv" ],
                        "teachers" : [ "khl" ]
                      }, {
                        "appointmentInstance" : 3276941,
                        "end" : "1730724300",
                        "id" : 3435022,
                        "locations" : [ "a128" ],
                        "start" : "1730721300",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278507,
                        "end" : "1731058200",
                        "id" : 3436575,
                        "locations" : [ "gym6" ],
                        "start" : "1731052200",
                        "subjects" : [ "lo" ],
                        "teachers" : [ "sld09" ]
                      }, {
                        "appointmentInstance" : 3276760,
                        "end" : "1730706600",
                        "id" : 3434682,
                        "locations" : [ "a028" ],
                        "start" : "1730703600",
                        "subjects" : [ "rek" ],
                        "teachers" : [ "men20" ]
                      }, {
                        "appointmentInstance" : 3278485,
                        "end" : "1730976000",
                        "id" : 3436268,
                        "locations" : [ "b149" ],
                        "start" : "1730973000",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278009,
                        "end" : "1730897100",
                        "id" : 3436029,
                        "locations" : [ "b119" ],
                        "start" : "1730894100",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3277073,
                        "end" : "1730712600",
                        "id" : 3434772,
                        "locations" : [ "a138" ],
                        "start" : "1730709600",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3277614,
                        "end" : "1730803200",
                        "id" : 3435501,
                        "locations" : [ "a118" ],
                        "start" : "1730800800",
                        "subjects" : [ "gs" ],
                        "teachers" : [ "wes" ]
                      }, {
                        "appointmentInstance" : 3278329,
                        "end" : "1730986500",
                        "id" : 3436430,
                        "locations" : [ "a138" ],
                        "start" : "1730983500",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "hgd", "kps", "hee", "khl", "hol", "ina", "hkp", "htg" ]
                      }, {
                        "appointmentInstance" : 3277797,
                        "end" : "1730968800",
                        "id" : 3435099,
                        "locations" : [ "binask2" ],
                        "start" : "1730965800",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3277284,
                        "end" : "1730797200",
                        "id" : 3435340,
                        "locations" : [ "a216" ],
                        "start" : "1730794800",
                        "subjects" : [ "bg" ],
                        "teachers" : [ "men20" ]
                      }, {
                        "appointmentInstance" : 3277212,
                        "end" : "1730800800",
                        "id" : 3435425,
                        "locations" : [ "b001" ],
                        "start" : "1730798400",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3278175,
                        "end" : "1730892600",
                        "id" : 3435970,
                        "locations" : [ "a132" ],
                        "start" : "1730889600",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3277986,
                        "end" : "1730882400",
                        "id" : 3435745,
                        "locations" : [ "a030" ],
                        "start" : "1730879400",
                        "subjects" : [ "ak" ],
                        "teachers" : [ "gra" ]
                      }, {
                        "appointmentInstance" : 3277989,
                        "end" : "1730889600",
                        "id" : 3435914,
                        "locations" : [ "binask6" ],
                        "start" : "1730886600",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3277655,
                        "end" : "1730794800",
                        "id" : 3435306,
                        "locations" : [ "a266" ],
                        "start" : "1730792400",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3278699,
                        "end" : "1731052200",
                        "id" : 3436536,
                        "locations" : [ "a028" ],
                        "start" : "1731049200",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278204,
                        "end" : "1730983500",
                        "id" : 3436360,
                        "locations" : [ "a120" ],
                        "start" : "1730980500",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3278747,
                        "end" : "1731069900",
                        "id" : 3436806,
                        "locations" : [ "b151" ],
                        "start" : "1731066900",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3278256,
                        "end" : "1730979000",
                        "id" : 3436273,
                        "locations" : [ "a028" ],
                        "start" : "1730976000",
                        "subjects" : [ "ak" ],
                        "teachers" : [ "gra" ]
                      } ],
                      "details" : "",
                      "message" : "",
                      "rowCount" : 30,
                      "statusCode" : 200
                    }
                  },
                  "Default" : {
                    "value" : {
                      "data" : [ {
                        "appointmentInstance" : 3276941,
                        "end" : "1730724300",
                        "id" : 3435022,
                        "locations" : [ "a128" ],
                        "start" : "1730721300",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278070,
                        "end" : "1730965800",
                        "id" : 3436163,
                        "locations" : [ "a268" ],
                        "start" : "1730962800",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3276789,
                        "end" : "1730709600",
                        "id" : 3434727,
                        "locations" : [ "a118" ],
                        "start" : "1730706600",
                        "subjects" : [ "gs" ],
                        "teachers" : [ "wes" ]
                      }, {
                        "appointmentInstance" : 3277464,
                        "end" : "1730792400",
                        "id" : 3435223,
                        "locations" : [ "a270" ],
                        "start" : "1730790000",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3277423,
                        "end" : "1730879400",
                        "id" : 3435716,
                        "locations" : [ "a252" ],
                        "start" : "1730876400",
                        "subjects" : [ "gd" ],
                        "teachers" : [ "too" ]
                      }, {
                        "appointmentInstance" : 3277073,
                        "end" : "1730712600",
                        "id" : 3434772,
                        "locations" : [ "a138" ],
                        "start" : "1730709600",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3277065,
                        "end" : "1730716800",
                        "id" : 3434858,
                        "locations" : [ "b129" ],
                        "start" : "1730713800",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3278009,
                        "end" : "1730897100",
                        "id" : 3436029,
                        "locations" : [ "b119" ],
                        "start" : "1730894100",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3277284,
                        "end" : "1730797200",
                        "id" : 3435340,
                        "locations" : [ "a216" ],
                        "start" : "1730794800",
                        "subjects" : [ "bg" ],
                        "teachers" : [ "men20" ]
                      }, {
                        "appointmentInstance" : 3277212,
                        "end" : "1730800800",
                        "id" : 3435425,
                        "locations" : [ "b001" ],
                        "start" : "1730798400",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3277993,
                        "end" : "1730885400",
                        "id" : 3435856,
                        "locations" : [ "a030" ],
                        "start" : "1730882400",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278204,
                        "end" : "1730983500",
                        "id" : 3436360,
                        "locations" : [ "a120" ],
                        "start" : "1730980500",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3277986,
                        "end" : "1730882400",
                        "id" : 3435745,
                        "locations" : [ "a030" ],
                        "start" : "1730879400",
                        "subjects" : [ "ak" ],
                        "teachers" : [ "gra" ]
                      }, {
                        "appointmentInstance" : 3277614,
                        "end" : "1730803200",
                        "id" : 3435501,
                        "locations" : [ "a118" ],
                        "start" : "1730800800",
                        "subjects" : [ "gs" ],
                        "teachers" : [ "wes" ]
                      }, {
                        "appointmentInstance" : 3278485,
                        "end" : "1730976000",
                        "id" : 3436268,
                        "locations" : [ "b149" ],
                        "start" : "1730973000",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278832,
                        "end" : "1731065400",
                        "id" : 3436675,
                        "locations" : [ "bv1" ],
                        "start" : "1731059400",
                        "subjects" : [ "bv" ],
                        "teachers" : [ "khl" ]
                      }, {
                        "appointmentInstance" : 3277797,
                        "end" : "1730968800",
                        "id" : 3435099,
                        "locations" : [ "binask2" ],
                        "start" : "1730965800",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3278747,
                        "end" : "1731069900",
                        "id" : 3436806,
                        "locations" : [ "b151" ],
                        "start" : "1731066900",
                        "subjects" : [ "du" ],
                        "teachers" : [ "gnt" ]
                      }, {
                        "appointmentInstance" : 3278175,
                        "end" : "1730892600",
                        "id" : 3435970,
                        "locations" : [ "a132" ],
                        "start" : "1730889600",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3277989,
                        "end" : "1730889600",
                        "id" : 3435914,
                        "locations" : [ "binask6" ],
                        "start" : "1730886600",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3278699,
                        "end" : "1731052200",
                        "id" : 3436536,
                        "locations" : [ "a028" ],
                        "start" : "1731049200",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "wro" ]
                      }, {
                        "appointmentInstance" : 3278507,
                        "end" : "1731058200",
                        "id" : 3436575,
                        "locations" : [ "gym6" ],
                        "start" : "1731052200",
                        "subjects" : [ "lo" ],
                        "teachers" : [ "sld09" ]
                      }, {
                        "appointmentInstance" : 3276826,
                        "end" : "1730719800",
                        "id" : 3434913,
                        "locations" : [ "b129" ],
                        "start" : "1730716800",
                        "subjects" : [ "fa" ],
                        "teachers" : [ "mno" ]
                      }, {
                        "appointmentInstance" : 3278979,
                        "end" : "1731072900",
                        "id" : 3436874,
                        "locations" : [ "binask10" ],
                        "start" : "1731069900",
                        "subjects" : [ "na" ],
                        "teachers" : [ "hkp" ]
                      }, {
                        "appointmentInstance" : 3278630,
                        "end" : "1730971800",
                        "id" : 3435143,
                        "locations" : [ "a152" ],
                        "start" : "1730968800",
                        "subjects" : [ "en" ],
                        "teachers" : [ "sld14" ]
                      }, {
                        "appointmentInstance" : 3277578,
                        "end" : "1730807100",
                        "id" : 3435563,
                        "locations" : [ "a212" ],
                        "start" : "1730804700",
                        "subjects" : [ "gd" ],
                        "teachers" : [ "too" ]
                      }, {
                        "appointmentInstance" : 3278256,
                        "end" : "1730979000",
                        "id" : 3436273,
                        "locations" : [ "a028" ],
                        "start" : "1730976000",
                        "subjects" : [ "ak" ],
                        "teachers" : [ "gra" ]
                      }, {
                        "appointmentInstance" : 3277655,
                        "end" : "1730794800",
                        "id" : 3435306,
                        "locations" : [ "a266" ],
                        "start" : "1730792400",
                        "subjects" : [ "ne" ],
                        "teachers" : [ "ned" ]
                      }, {
                        "appointmentInstance" : 3276760,
                        "end" : "1730706600",
                        "id" : 3434682,
                        "locations" : [ "a028" ],
                        "start" : "1730703600",
                        "subjects" : [ "rek" ],
                        "teachers" : [ "men20" ]
                      }, {
                        "appointmentInstance" : 3278329,
                        "end" : "1730986500",
                        "id" : 3436430,
                        "locations" : [ "a138" ],
                        "start" : "1730983500",
                        "subjects" : [ "wi" ],
                        "teachers" : [ "khl", "hee", "hol", "kps", "hkp", "hgd", "ina", "htg" ]
                      } ],
                      "details" : "",
                      "message" : "",
                      "rowCount" : 30,
                      "statusCode" : 200
                    }
                  }
                }
              }
            }
          },
          "403" : {
            "description" : "Zermelo Error",
            "headers" : {
              "Access-Control-Allow-Headers" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Content-Type, Authorization"
                }
              },
              "Access-Control-Allow-Methods" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "GET, POST, PUT, DELETE"
                }
              },
              "Access-Control-Allow-Origin" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "*"
                }
              },
              "Connection" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "close"
                }
              },
              "Date" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "Tue, 05 Nov 2024 19:12:05 GMT"
                }
              },
              "Host" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "localhost:8000"
                }
              },
              "X-Powered-By" : {
                "style" : "simple",
                "explode" : false,
                "schema" : {
                  "type" : "string",
                  "example" : "PHP/8.3.12"
                }
              }
            },
            "content" : {
              "application/json" : {
                "schema" : {
                  "$ref" : "#/components/schemas/inline_response_403"
                },
                "examples" : {
                  "Zermelo Error" : {
                    "value" : {
                      "data" : [ ],
                      "details" : "U heeft niet voldoende rechten om te zoeken op (deze waarde van) valid of het veld bestaat niet. Details: SecurityRuleException: U heeft niet voldoende rechten om te zoeken op (deze waarde van) valid of het veld bestaat niet",
                      "message" : "An error occurred while fetching data from Zermelo",
                      "rowCount" : 0,
                      "statusCode" : 403
                    }
                  }
                }
              }
            }
          }
        },
        "security" : [ {
          "bearerAuth" : [ ]
        } ]
      }
    },
    "/v1/school": {
      "get": {
        "summary": "Retrieve list of schools",
        "description": "This endpoint retrieves a list of schools for a specific year.",
        "operationId": "getSchools",
        "responses": {
          "200": {
            "description": "A list of schools.",
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 200,
                  "message": "",
                  "details": "",
                  "rowCount": 5,
                  "data": [
                    {
                      "schoolInSchoolYearId": 1001452,
                      "schoolId": 1000552,
                      "schoolYear": 2024,
                      "projectName": "De MAVO 2024-2025",
                      "schoolName": "De MAVO"
                    },
                    {
                      "schoolInSchoolYearId": 1001602,
                      "schoolId": 101,
                      "schoolYear": 2024,
                      "projectName": "School met bijgebouw 2024-2025",
                      "schoolName": "School met bijgebouw"
                    }
                  ]
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" },
                    "details": { "type": "string" },
                    "rowCount": { "type": "number" },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "schoolInSchoolYearId": { "type": "number" },
                          "schoolId": { "type": "number" },
                          "schoolYear": { "type": "number" },
                          "projectName": { "type": "string" },
                          "schoolName": { "type": "string" }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/v1/school/{id}": {
      "get": {
        "summary": "Retrieve details of a school",
        "description": "This endpoint retrieves detailed information about a specific school.",
        "operationId": "getSchoolById",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "ID of the school",
            "schema": {
              "type": "number",
              "example": 1001452
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Details of a school.",
            "content": {
              "application/json": {
                "example": {
                  "statusCode": 200,
                  "message": "",
                  "details": "",
                  "rowCount": 1,
                  "data": [
                    {
                      "schoolInSchoolYearId": 1001452,
                      "schoolId": 1000552,
                      "schoolYear": 2024,
                      "projectName": "De MAVO 2024-2025",
                      "schoolName": "De MAVO"
                    }
                  ]
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "statusCode": { "type": "number" },
                    "message": { "type": "string" },
                    "details": { "type": "string" },
                    "rowCount": { "type": "number" },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "schoolInSchoolYearId": { "type": "number" },
                          "schoolId": { "type": "number" },
                          "schoolYear": { "type": "number" },
                          "projectName": { "type": "string" },
                          "schoolName": { "type": "string" }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components" : {
    "schemas" : {
      "inline_response_200_1_data" : {
        "type" : "object",
        "properties" : {
          "appointmentInstance" : {
            "type" : "number",
            "example" : 3276941
          },
          "end" : {
            "type" : "string",
            "example" : "1730724300"
          },
          "id" : {
            "type" : "number",
            "example" : 3435022
          },
          "locations" : {
            "type" : "array",
            "example" : [ "a128" ],
            "items" : {
              "type" : "string",
              "example" : "a128"
            }
          },
          "start" : {
            "type" : "string",
            "example" : "1730721300"
          },
          "subjects" : {
            "type" : "array",
            "example" : [ "wi" ],
            "items" : {
              "type" : "string",
              "example" : "wi"
            }
          },
          "teachers" : {
            "type" : "array",
            "example" : [ "wro" ],
            "items" : {
              "type" : "string",
              "example" : "wro"
            }
          }
        }
      },
      "inline_response_404" : {
        "type" : "object",
        "properties" : {
          "data" : {
            "type" : "array",
            "example" : [ ],
            "items" : { }
          },
          "details" : {
            "type" : "string",
            "example" : "The user could not be found in the Zermelo API"
          },
          "message" : {
            "type" : "string",
            "example" : "User not found"
          },
          "rowCount" : {
            "type" : "number",
            "example" : 0
          },
          "statusCode" : {
            "type" : "number",
            "example" : 404
          }
        }
      },
      "inline_response_200_1" : {
        "type" : "object",
        "properties" : {
          "data" : {
            "type" : "array",
            "example" : [ {
              "appointmentInstance" : 3276941,
              "end" : "1730724300",
              "id" : 3435022,
              "locations" : [ "a128" ],
              "start" : "1730721300",
              "subjects" : [ "wi" ],
              "teachers" : [ "wro" ]
            }, {
              "appointmentInstance" : 3278070,
              "end" : "1730965800",
              "id" : 3436163,
              "locations" : [ "a268" ],
              "start" : "1730962800",
              "subjects" : [ "ne" ],
              "teachers" : [ "ned" ]
            }, {
              "appointmentInstance" : 3276789,
              "end" : "1730709600",
              "id" : 3434727,
              "locations" : [ "a118" ],
              "start" : "1730706600",
              "subjects" : [ "gs" ],
              "teachers" : [ "wes" ]
            }, {
              "appointmentInstance" : 3277464,
              "end" : "1730792400",
              "id" : 3435223,
              "locations" : [ "a270" ],
              "start" : "1730790000",
              "subjects" : [ "du" ],
              "teachers" : [ "gnt" ]
            }, {
              "appointmentInstance" : 3277423,
              "end" : "1730879400",
              "id" : 3435716,
              "locations" : [ "a252" ],
              "start" : "1730876400",
              "subjects" : [ "gd" ],
              "teachers" : [ "too" ]
            }, {
              "appointmentInstance" : 3277073,
              "end" : "1730712600",
              "id" : 3434772,
              "locations" : [ "a138" ],
              "start" : "1730709600",
              "subjects" : [ "du" ],
              "teachers" : [ "gnt" ]
            }, {
              "appointmentInstance" : 3277065,
              "end" : "1730716800",
              "id" : 3434858,
              "locations" : [ "b129" ],
              "start" : "1730713800",
              "subjects" : [ "en" ],
              "teachers" : [ "sld14" ]
            }, {
              "appointmentInstance" : 3278009,
              "end" : "1730897100",
              "id" : 3436029,
              "locations" : [ "b119" ],
              "start" : "1730894100",
              "subjects" : [ "fa" ],
              "teachers" : [ "mno" ]
            }, {
              "appointmentInstance" : 3277284,
              "end" : "1730797200",
              "id" : 3435340,
              "locations" : [ "a216" ],
              "start" : "1730794800",
              "subjects" : [ "bg" ],
              "teachers" : [ "men20" ]
            }, {
              "appointmentInstance" : 3277212,
              "end" : "1730800800",
              "id" : 3435425,
              "locations" : [ "b001" ],
              "start" : "1730798400",
              "subjects" : [ "en" ],
              "teachers" : [ "sld14" ]
            }, {
              "appointmentInstance" : 3277993,
              "end" : "1730885400",
              "id" : 3435856,
              "locations" : [ "a030" ],
              "start" : "1730882400",
              "subjects" : [ "wi" ],
              "teachers" : [ "wro" ]
            }, {
              "appointmentInstance" : 3278204,
              "end" : "1730983500",
              "id" : 3436360,
              "locations" : [ "a120" ],
              "start" : "1730980500",
              "subjects" : [ "fa" ],
              "teachers" : [ "mno" ]
            }, {
              "appointmentInstance" : 3277986,
              "end" : "1730882400",
              "id" : 3435745,
              "locations" : [ "a030" ],
              "start" : "1730879400",
              "subjects" : [ "ak" ],
              "teachers" : [ "gra" ]
            }, {
              "appointmentInstance" : 3277614,
              "end" : "1730803200",
              "id" : 3435501,
              "locations" : [ "a118" ],
              "start" : "1730800800",
              "subjects" : [ "gs" ],
              "teachers" : [ "wes" ]
            }, {
              "appointmentInstance" : 3278485,
              "end" : "1730976000",
              "id" : 3436268,
              "locations" : [ "b149" ],
              "start" : "1730973000",
              "subjects" : [ "wi" ],
              "teachers" : [ "wro" ]
            }, {
              "appointmentInstance" : 3278832,
              "end" : "1731065400",
              "id" : 3436675,
              "locations" : [ "bv1" ],
              "start" : "1731059400",
              "subjects" : [ "bv" ],
              "teachers" : [ "khl" ]
            }, {
              "appointmentInstance" : 3277797,
              "end" : "1730968800",
              "id" : 3435099,
              "locations" : [ "binask2" ],
              "start" : "1730965800",
              "subjects" : [ "na" ],
              "teachers" : [ "hkp" ]
            }, {
              "appointmentInstance" : 3278747,
              "end" : "1731069900",
              "id" : 3436806,
              "locations" : [ "b151" ],
              "start" : "1731066900",
              "subjects" : [ "du" ],
              "teachers" : [ "gnt" ]
            }, {
              "appointmentInstance" : 3278175,
              "end" : "1730892600",
              "id" : 3435970,
              "locations" : [ "a132" ],
              "start" : "1730889600",
              "subjects" : [ "ne" ],
              "teachers" : [ "ned" ]
            }, {
              "appointmentInstance" : 3277989,
              "end" : "1730889600",
              "id" : 3435914,
              "locations" : [ "binask6" ],
              "start" : "1730886600",
              "subjects" : [ "na" ],
              "teachers" : [ "hkp" ]
            }, {
              "appointmentInstance" : 3278699,
              "end" : "1731052200",
              "id" : 3436536,
              "locations" : [ "a028" ],
              "start" : "1731049200",
              "subjects" : [ "wi" ],
              "teachers" : [ "wro" ]
            }, {
              "appointmentInstance" : 3278507,
              "end" : "1731058200",
              "id" : 3436575,
              "locations" : [ "gym6" ],
              "start" : "1731052200",
              "subjects" : [ "lo" ],
              "teachers" : [ "sld09" ]
            }, {
              "appointmentInstance" : 3276826,
              "end" : "1730719800",
              "id" : 3434913,
              "locations" : [ "b129" ],
              "start" : "1730716800",
              "subjects" : [ "fa" ],
              "teachers" : [ "mno" ]
            }, {
              "appointmentInstance" : 3278979,
              "end" : "1731072900",
              "id" : 3436874,
              "locations" : [ "binask10" ],
              "start" : "1731069900",
              "subjects" : [ "na" ],
              "teachers" : [ "hkp" ]
            }, {
              "appointmentInstance" : 3278630,
              "end" : "1730971800",
              "id" : 3435143,
              "locations" : [ "a152" ],
              "start" : "1730968800",
              "subjects" : [ "en" ],
              "teachers" : [ "sld14" ]
            }, {
              "appointmentInstance" : 3277578,
              "end" : "1730807100",
              "id" : 3435563,
              "locations" : [ "a212" ],
              "start" : "1730804700",
              "subjects" : [ "gd" ],
              "teachers" : [ "too" ]
            }, {
              "appointmentInstance" : 3278256,
              "end" : "1730979000",
              "id" : 3436273,
              "locations" : [ "a028" ],
              "start" : "1730976000",
              "subjects" : [ "ak" ],
              "teachers" : [ "gra" ]
            }, {
              "appointmentInstance" : 3277655,
              "end" : "1730794800",
              "id" : 3435306,
              "locations" : [ "a266" ],
              "start" : "1730792400",
              "subjects" : [ "ne" ],
              "teachers" : [ "ned" ]
            }, {
              "appointmentInstance" : 3276760,
              "end" : "1730706600",
              "id" : 3434682,
              "locations" : [ "a028" ],
              "start" : "1730703600",
              "subjects" : [ "rek" ],
              "teachers" : [ "men20" ]
            }, {
              "appointmentInstance" : 3278329,
              "end" : "1730986500",
              "id" : 3436430,
              "locations" : [ "a138" ],
              "start" : "1730983500",
              "subjects" : [ "wi" ],
              "teachers" : [ "khl", "hee", "hol", "kps", "hkp", "hgd", "ina", "htg" ]
            } ],
            "items" : {
              "$ref" : "#/components/schemas/inline_response_200_1_data"
            }
          },
          "details" : {
            "type" : "string",
            "example" : ""
          },
          "message" : {
            "type" : "string",
            "example" : ""
          },
          "rowCount" : {
            "type" : "number",
            "example" : 30
          },
          "statusCode" : {
            "type" : "number",
            "example" : 200
          }
        }
      },
      "inline_response_200" : {
        "type" : "object",
        "properties" : {
          "data" : {
            "type" : "array",
            "example" : [ {
              "code" : "vis",
              "firstName" : "Sienna",
              "lastName" : "Visscher",
              "prefix" : "van der"
            } ],
            "items" : {
              "$ref" : "#/components/schemas/inline_response_200_data"
            }
          },
          "details" : {
            "type" : "string",
            "example" : ""
          },
          "message" : {
            "type" : "string",
            "example" : ""
          },
          "rowCount" : {
            "type" : "number",
            "example" : 1
          },
          "statusCode" : {
            "type" : "number",
            "example" : 200
          }
        }
      },
      "inline_response_403" : {
        "type" : "object",
        "properties" : {
          "data" : {
            "type" : "array",
            "example" : [ ],
            "items" : { }
          },
          "details" : {
            "type" : "string",
            "example" : "U heeft niet voldoende rechten om te zoeken op (deze waarde van) valid of het veld bestaat niet. Details: SecurityRuleException: U heeft niet voldoende rechten om te zoeken op (deze waarde van) valid of het veld bestaat niet"
          },
          "message" : {
            "type" : "string",
            "example" : "An error occurred while fetching data from Zermelo"
          },
          "rowCount" : {
            "type" : "number",
            "example" : 0
          },
          "statusCode" : {
            "type" : "number",
            "example" : 403
          }
        }
      },
      "inline_response_200_data" : {
        "type" : "object",
        "properties" : {
          "code" : {
            "type" : "string",
            "example" : "vis"
          },
          "firstName" : {
            "type" : "string",
            "example" : "Sienna"
          },
          "lastName" : {
            "type" : "string",
            "example" : "Visscher"
          },
          "prefix" : {
            "type" : "string",
            "example" : "van der"
          }
        }
      }
    },
    "securitySchemes" : {
      "bearerAuth" : {
        "type" : "http",
        "scheme" : "bearer"
      }
    }
  }
}